#cloud-config
# This is the boot time cofiguration to the VSI. Here we install the JAVA pacakge to run java app
# tar and firewalld to run some commands.
# firewall commands will be used to add the service and open the ports on the VSI.

runcmd: 
##### install tar package used in the scripts   
   - yum install -y tar 
##### install the application run time    
   - yum install -y java 
##### install firewalld package to updated the firewall
   - yum install -y firewalld   
   - sudo systemctl stop firewalld   
   - sudo firewall-offline-cmd --zone=public --add-service=http 
   - sudo firewall-offline-cmd --zone=public --add-service=https 
   - sudo firewall-offline-cmd --service=https --add-port=${app_port}/tcp  
   - sudo firewall-offline-cmd --service=https --add-port=${health_port}/tcp  
   - sudo systemctl start firewalld 
